# Basic workflow

In this section, we will show a basic workflow for performing an E~max~ model 
analysis for continuous endpoint.

## Setup and load

```{r}
#| output: FALSE
#| message: FALSE

library(tidyverse)
library(BayesERtools)
library(posterior)
library(tidybayes)
library(here)
library(gt)

theme_set(theme_bw(base_size = 12))
```

```{r}
#| include: FALSE
# Enable colored outputs
source(here("R", "cli_color_text.R"))
```


## Load data

```{r}
#| label: fig-data-look
#| message: FALSE

d_example_emax_nocov <- read_csv(here("data", "d_example_emax_nocov.csv"))

d_example_emax_nocov |>
  head() |>
  gt() |>
  fmt_number(decimals = 2)

ggplot(d_example_emax_nocov, aes(Conc, Y)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method = "loess", se = F, col = "darkgrey")
```

## Sigmoidal E~max~ model

```{r}
set.seed(1234)

ermod_sigemax <- dev_ermod_emax(
  data = d_example_emax_nocov,
  var_resp = "Y",
  var_exposure = "Conc",
  gamma_fix = NULL
)

ermod_sigemax
```

## Observation vs model fit

```{r}
#| label: fig-plot-er
#| fig-width: 7
#| fig-height: 5

d_sim_ermod_sigemax <-
  sim_er(ermod_sigemax, output_type = c("median_qi"))

plot_er_gof(d_sim_ermod_sigemax)
```

## Parameter estimates

```{r}
d_draws_sigemax <- as_draws_df(ermod_sigemax)

d_draws_sigemax_summary <-
  summarize_draws(d_draws_sigemax)

ec50_mean <-
  d_draws_sigemax_summary |>
  filter(variable == "ec50") |>
  pull(mean)

d_draws_sigemax_summary |>
  gt() |>
  fmt_number(decimals = 2)
```


## Prediction at a certain concentrations

```{r}
#| label: fig-plot-er-new-conc
#| fig-width: 7
#| fig-height: 5

d_sim_new_conc <-
  sim_er_new_exp(ermod_sigemax,
    exposure_to_sim_vec  = c(10, 20, 30, 50),
    output_type = c("median_qi"))

d_sim_new_conc |>
  select(-starts_with(".linpred"), -c(.row, .width, .point, .interval)) |>
  gt() |>
  fmt_number(decimals = 2) |>
  tab_header(
    title = md("Prediction at specific concentrations")
  )

d_sim_ermod_sigemax |>
  ggplot(aes(x = Conc, y = Y)) +
  # Emax model curve
  geom_vline(xintercept = ec50_mean, linetype = "dashed", color = "deepskyblue") +
  geom_ribbon(aes(y = .epred, ymin = .epred.lower, ymax = .epred.upper),
    alpha = 0.3, fill = "deepskyblue") +
  geom_line(aes(y = .epred), color = "deepskyblue") +
  # Observed data
  geom_point(data = d_example_emax_nocov, color = "grey") +
  # Prediction at the specified doses
  geom_point(data = d_sim_new_conc, aes(y = .epred), color = "tomato", size = 3) +
  geom_errorbar(data = d_sim_new_conc,
    aes(y = .epred, ymin = .epred.lower, ymax = .epred.upper),
    width = 1, color = "tomato") +
  coord_cartesian(ylim = c(-1, 17)) +
  scale_fill_brewer(palette = "Greys") +
  labs(
    title = "Sigmoidal E~max~ model predictions at new exposure levels",
    caption =
      "vertical dashed line: estimated EC~50~ value<br>area: 95% credible interval") +
  theme(plot.title = ggtext::element_markdown(),
    plot.caption = ggtext::element_markdown())
```
